In [1]:
# use these magic spells to update your classes methods on-the-fly as you edit them:
%reload_ext autoreload
%autoreload 2
from pprint import pprint
from IPython.core.display import display, HTML, Markdown
import ipywidgets as widgets
# %run includeme.ipynb # include a notebook from this same directory
display(HTML("<style>.container { width:100% !important; }</style>"))

In [2]:
import logging
import numpy as np
from skeleton import FancyHelloWorld
from skeleton.tools import quickLog

NOTE: cpp extension loaded from /home/sampsa/python3_packages/skeleton/skeleton/skeleton_cpp/skeleton_cpp/skeleton_cpp_module.py and from /home/sampsa/python3_packages/skeleton/skeleton/_skeleton_cpp_module.cpython-38-x86_64-linux-gnu.so FEEL FREE TO REMOVE THIS MESSAGE



In [3]:
quickLog("FancyHelloWorld", logging.DEBUG)

<Logger FancyHelloWorld (DEBUG)>

In [4]:
greeter = FancyHelloWorld(person="me")

FancyHelloWorld - INFO - info level msg from __init__
FancyHelloWorld - DEBUG - debug level msg from __init__


In [5]:
print(greeter)

**************
Hello from me
**************



In [6]:
# edit the code in ../skeleton/greeters/fancy.py for someMethod to print another message and then run that line above again
# you'll notice that the code has been refreshed automagically

In [7]:
# let's test the cpp module

In [8]:
from skeleton import cpp_module

In [9]:
t = cpp_module.Test()

In [10]:
t.callme() # this prints "hello from cpp" .. but to the terminal! (since the output is not handled by python, but by c++)

In [11]:
tester = cpp_module.TestNumpy()

In [12]:
a=np.ones((10,10))

In [13]:
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [14]:
tester.setZero(a)

In [15]:
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
a=np.ones((10,10))

In [17]:
line=tester.doodle2D(a)

In [18]:
line

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10.])